library(data.table)
DF <- fread("household_power_consumption.txt",sep=";",select=c("Date","Time","Global_active_power"),na.strings=c("NA","","?"))
data <- subset(DF,as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-01") | as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-02") )
library(datasets)
data$Global_active_power <- as.numeric(data$Global_active_power)
png("plot1.png",width=480,height=480)
hist(data$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()
rm(data)
rm(DF)