library(data.table)
DF <- fread("household_power_consumption.txt",sep=";",select=c("Date","Time","Sub_metering_1","Sub_metering_2","Sub_metering_3"),na.strings=c("NA","","?"))
data <- subset(DF,as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-01") | as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-02") )
library(datasets)
png("plot3.png",width=480,height=480)
plot(data$Sub_metering_1 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),type="l",xlab="",ylab="Energy sub metering",main="",col="black")
lines(data$Sub_metering_2 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="red",type="l")
lines(data$Sub_metering_3 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=2)
dev.off()
rm(data)
rm(DF)