library(data.table)
DF <- fread("household_power_consumption.txt",sep=";",na.strings=c("NA","","?"))
data <- subset(DF,as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-01") | as.Date(Date,format="%d/%m/%Y") == as.Date("2007-02-02") )
library(datasets)
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(data$Global_active_power ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),type="l",xlab="",ylab="Global Active Power",main="")
plot(data$Voltage ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),type="l",xlab="datetime",ylab="Voltage",main="")
plot(data$Sub_metering_1 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),type="l",xlab="",ylab="Energy sub metering",main="",col="black")
lines(data$Sub_metering_2 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="red",type="l")
lines(data$Sub_metering_3 ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=2,box.lwd=0)
plot(data$Global_reactive_power ~ as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),type="l",xlab="datetime",ylab="Global_reactive_power",main="")
dev.off()
rm(data)
rm(DF)